env = Environment(CC = 'gcc',
                  CCFLAGS = ['-Wall','-O3','-ffast-math'],
                  CPPPATH = ['.'])

objlist = env.Object(['vmblock.cpp', 'basis_r.cpp'])

env.Program(['carpol2.cpp', objlist])
