#
# Copyright (c) 2004-2026 Jean-Luc Thiffeault <jeanluc@mailaps.org>
#
# See the file LICENSE for copying permission.
#

SConscript('SConscript')
Import(['env','matlabenv','lapackenv','csparseenv','boost_timerenv'])

progs = ['display_task_test','finitediff_test','math_test','mathvector_test',
         'qrdecomp_test','polynomial_test','stlio_demo','vcs_test',
         'freeword_test','freeauto_test']

# These require linking against LAPACK.
lapackprogs = ['eigensystem_test','svdecomp_test']

for p in progs:
    env.Program(p + '.cpp')
for p in lapackprogs:
    lapackenv.Program(p + '.cpp')

matlabenv.Program('matlab_mathematica_test.cpp')

csparseenv.Program('csparse_test.cpp')

boost_timerenv.Program('tictoc_test.cpp')
