#
# Copyright (c) 2004-2014 Jean-Luc Thiffeault <jeanluc@mailaps.org>
#
# See the file LICENSE for copying permission.
#

SConscript('SConscript')
Import(['env','matlabenv','lapackenv','csparseenv'])

progs = ['finitediff_err_test','finitediff_test','finitediff_vec_test',
         'math_test','mathvector_test','qr_test','tictoc_test',
         'polynomial_test','vcs_test']

# These require linking against LAPACK.
lapackprogs = ['eigensystem_test','svd_test']

for p in progs:
    env.Program(p + '.cpp')
for p in lapackprogs:
    lapackenv.Program(p + '.cpp')

matlabenv.Program('matlab_test.cpp')

csparseenv.Program('csparse_test.cpp')
