SConscript('SConscript')
Import(['env','matlabenv','lapackenv','csparseenv'])

progs = ['finitediff','finitediff_err','finitediff_vec','vcs_banner',
         'mathvector','precisionmath','qrtest','tictoc_test','polytest']

# These require linking against LAPACK.
lapackprogs = ['eigensystem','svdtest']

for p in progs:
    env.Program(p + '.cpp')
for p in lapackprogs:
    lapackenv.Program(p + '.cpp')

matlabenv.Program('matlabtest.cpp')

csparseenv.Program('csparsetest.cpp')
